#spring.data.mongodb.host:localhost
#spring.data.mongodb.port:27017
spring.data.mongodb.uri: mongodb+srv://sp1137725:sp1137725@cluster0.lwfox.mongodb.net/?appName=Cluster0
spring.data.mongodb.database:journaldb
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.security=DEBUG
